## CHANGE this to the name of your plugin.
name: IslandWipe

## CHANGE this to your username.
author: NCBPFluffyBear

## CHANGE this to a meaninful but short description of your plugin.
description: Clears Slimefun data from a SuperiorSkyblock island

## CHANGE this to the path of the class that extends JavaPlugin.
main: me.ncbpfluffybear.islandwipe.IslandWipe

## You can change this to link to your website or repository. You can also remove this line if you want to.
website: https://github.com/TheBusyBiscuit/Slimefun4-Addon

## This is required and marks Slimefun as a plugin dependency.
depend: [Slimefun]

## This value is automatically replaced by the version specified in your pom.xml file, do not change this.
version: 1.0.0

## This is the minimum minecraft version required to run your plugin.
api-version: 1.16

commands:
  islandwipe:
    description: IslandWipe Command
    usage: /<command>

  findghost:
    description: Command used to find ghost blocks
    usage: /<command>
    aliases: [fg]

permissions:
  islandwipe.admin:
    description: Allows you to use IslandWipe admin commands